### ISSUE TITLE
Why isn't this a shell script?

### ISSUE THREAD

**Issue by Lewiscowles1986** [BytemarkHosting/pi-init2#2]
Apologies, this is your repo, you may do as you wish, but have you considered not writing shell commands into go? It seems like it would make a really simple shell-script without the need for a dependency on go or a build-step, and could help people to understand the main work is in overriding the init portion of the cmdline.txt to run a custom script. Also the custom script would be a lot more readable in shell.

**Comment by matthewbloch** [comment]
Hi Lewis, I agree a script would be more accessible. But it can't be a shell script because the Linux kernel can't directly execute that - init must be a standalone binary. And even if we had a shell (which we'd still need to build), it would rely on even more binaries like mknod, pivot_root etc. (which would also need building). 

So you could probably do all of the above with some hacks to busybox, but you'd still have a build step and it would be much more involved.

**Comment by Lewiscowles1986** [comment]
@matthewbloch init scripts can be run, it's what raspbian executes. The main difference is I suppose that you need to mount another partition that windows users won't have access to in order to have bash and linux available.

I've actually started a kiosk over the weekend after checking out what you did, you might like to have a look as it has no external dependencies from stock raspbian PIXEL; and is basically two files systemd service, and shell-script and an easily automated build step.

https://github.com/CODESIGN2/rpi-pixel-kiosk
